// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::DateTime;
use chrono::offset::Utc;
#[derive(Queryable, Debug)]
pub struct Category {
    pub id: i32,
    pub name: Option<String>,
    pub createdAt: Option<DateTime<Utc>>,
}

#[derive(Queryable, Debug)]
pub struct Post {
    pub id: i64,
    pub createdAt: DateTime<Utc>,
    pub title: String,
    pub subtitle: String,
    pub content: String,
    pub published: bool,
    pub authorId: i32,
    pub categoryId: i32,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub createdAt: DateTime<Utc>,
    pub email: String,
    pub name: String,
}

